---
title: "RNAseq local response"
author: "Sara Hoefer"
date: "2026-07-27"
output: html_document
---

# 1. Packages
```{r}
library(pheatmap)
library(ggplot2)
library(DESeq2)
library(dplyr)
library(RColorBrewer) # to change colors in pheatmap
library(tidyverse)

## to install DESeq2:
# if (!require("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# 
# BiocManager::install("DESeq2")
```

# 2. Functions
```{r}
se <- function (x) {sd (x,na.rm =TRUE) / sqrt (length(na.exclude (x)))}
```


# 3. Data
## 3.1. Load data

```{r}
dat_raw_counts <- read.table("03_local_response_RNAseq/01_data/within_leaf_analysis_ready_gene_counts.tsv",
                             header = T, row.names = 1, sep = "\t")

dat_fpkm <- read.table("03_local_response_RNAseq/01_data/within_leaf_analysis_ready_gene_fpkm_all_samples.tsv",
                             header = T, row.names = 1, sep = "\t")

dat_goi <- read.table("03_local_response_RNAseq/01_data/tristan_heatmap_gene_categories.csv",
                      header = T, sep = ",")

dat_phytohormone_goi <- read.table("03_local_response_RNAseq/01_data/phytohormone_candidates_gene_list.csv",
                                   header = T, sep = ",")

dat_meta <- read.table("03_local_response_RNAseq/01_data/within_leaf_analysis_ready_info.csv",
                             header = T, sep = ",")
```

## 3.2. Wrangle data

```{r}
# create col segment in metadata

dat_meta$segment <- sub(".*(S.).*", "\\1", dat_meta$sample_description)


# change phytohormone Gene_ID_v5 to Gene_ID

dat_ph_goi <- dat_phytohormone_goi |>
  mutate(Gene_ID = Gene_ID_v5)
```


# 4. Heatmap
## 4.1. DESeq2 for heatmap

```{r}

# 1. Create DESeq2 object (Replace with your actual data frames)
# countData: matrix of raw gene counts
# colData: dataframe with sample metadata, last condition is the default comparison (so it's treat vs. ctrl)

genotypes <- unique(dat_meta$genotype)
segments <- unique(dat_meta$segment)

results_list <- list()
dds_list <- list()

for(g in genotypes){
  for(s in segments){

    keep <- dat_meta$genotype == g &
            dat_meta$segment == s

    dds_sub <- DESeqDataSetFromMatrix(
      countData = dat_subset_ph[, keep],
      colData = dat_meta[keep, ],
      design = ~ condition_group
    )

    dds_sub <- DESeq(dds_sub)

    res <- results(dds_sub,
                   contrast = c("condition_group", "w", "c"))

    results_list[[paste(g, s, sep = "_")]] <- res
    dds_list[[paste(g, s, sep = "_")]] <- dds_sub
  }
}

```

```{r}
# create matrix for heatmap

for (name in c(
  "kn_S1", "kn_S2", "kn_S3",
  "lox_S1", "lox_S2", "lox_S3",
  "haci_S1", "haci_S2", "haci_S3"
)) {

  # DESeq2 results
  res <- as.data.frame(results_list[[name]])

  # VST transform
  vst_data <- varianceStabilizingTransformation(
    dds_list[[name]],
    blind = FALSE
  )

  vst_matrix <- assay(vst_data)

  # scale each gene
  heatmap_matrix <- t(scale(t(vst_matrix)))

  # get treatment labels
  condition <- colData(dds_list[[name]])$condition_group

  # average replicates
  heatmap_avg <- sapply(
    levels(condition),
    function(x) {
      rowMeans(heatmap_matrix[, condition == x, drop = FALSE])
    }
  )

  # reorder rows according to dat_phytohormone_goi order
  row_order <- match(dat_phytohormone_goi$Gene_ID_v5, rownames(heatmap_avg))
  row_order <- row_order[!is.na(row_order)]

  heatmap_avg <- heatmap_avg[row_order, ]

  # replace row names with gene names
  gene_names <- dat_phytohormone_goi$gene_name[
    match(rownames(heatmap_avg), dat_phytohormone_goi$Gene_ID_v5)
  ]

  rownames(heatmap_avg) <- gene_names
  colnames(heatmap_avg) <- c("Control", "MW")


  ## star matrix for this name only
  
  star_matrix <- matrix(
    "",
    nrow = nrow(heatmap_avg),
    ncol = 1,
    dimnames = list(
      rownames(heatmap_avg),
      name
    )
  )

  res <- results_list[[name]]

  common <- intersect(rownames(res), rownames(star_matrix))

  padj <- res[common, "padj"]

  star_matrix[common[!is.na(padj) & padj < 0.001], name] <- "***"
  star_matrix[common[!is.na(padj) & padj < 0.01 & padj >= 0.001], name] <- "**"
  star_matrix[common[!is.na(padj) & padj < 0.05 & padj >= 0.01], name] <- "*"


  # make stars match heatmap dimensions
  stars <- matrix(
    "",
    nrow = nrow(heatmap_avg),
    ncol = ncol(heatmap_avg),
    dimnames = dimnames(heatmap_avg)
  )

  stars[, "MW"] <- star_matrix[, name]


  ## save heatmap
  
  # pdf(paste0(name, "_hm2.pdf"), width = 5, height = 12)

  pheatmap(
    heatmap_avg,
    display_numbers = stars,
    cluster_cols = FALSE,
    cluster_rows = FALSE,
    show_rownames = TRUE,
    fontsize_col = 12,
    fontsize_row = 10,
    cellwidth = 10,
    cellheight = 10,
    main = name
  )

  # dev.off()
}
```

# 5. Barplots log-fold change

## 5.1. Subset of genes

Loop for everything from ChatGPT:

```{r}

# ---------------------------------------------------------
# Prepare metadata
# ---------------------------------------------------------

rownames(dat_meta) <- dat_meta$sample_description

# Make sure count matrix follows metadata order
dat_raw_counts <- dat_raw_counts[, rownames(dat_meta)]

# Factors
dat_meta$genotype <- factor(
  dat_meta$genotype,
  levels = c("kn", "lox", "haci")
)

dat_meta$condition_group <- factor(
  dat_meta$condition_group,
  levels = c("w", "c")
)

dat_meta$segment <- factor(
  dat_meta$segment,
  levels = c("S1", "S2", "S3")
)


# ---------------------------------------------------------
# Function
# ---------------------------------------------------------

make_segment_plot <- function(segment_name,
                              counts,
                              metadata,
                              goi,
                              padj_cutoff = 0.05) {
  
  # -------------------------------------------------------
  # 1. Subset metadata and counts for this segment
  # -------------------------------------------------------
  
  meta_seg <- metadata %>%
    filter(segment == segment_name)
  
  counts_seg <- counts[, rownames(meta_seg)]
  
  
  # -------------------------------------------------------
  # 2. Create DESeq2 object
  # -------------------------------------------------------
  
  dds <- DESeqDataSetFromMatrix(
    countData = round(as.matrix(counts_seg)),
    colData = meta_seg,
    design = ~ genotype + condition_group +
              genotype:condition_group
  )
  
  
  # -------------------------------------------------------
  # 3. Filter low-count genes
  # -------------------------------------------------------
  
  keep <- rowSums(counts(dds) >= 10) >= 2
  dds <- dds[keep, ]
  
  
  # -------------------------------------------------------
  # 4. Run DESeq2
  # -------------------------------------------------------
  
  dds <- DESeq(dds)
  
  
  # -------------------------------------------------------
  # 5. Interaction tests
  #
  # Does the C-vs-W response differ between:
  #   WT vs lox
  #   WT vs haci
  # -------------------------------------------------------
  
  res_lox_interaction <- results(
    dds,
    name = "genotypelox.condition_groupc"
  )
  
  res_haci_interaction <- results(
    dds,
    name = "genotypehaci.condition_groupc"
  )
  
  
  # -------------------------------------------------------
  # 6. Significant interaction genes
  # -------------------------------------------------------
  
  sig_lox <- rownames(res_lox_interaction)[
    !is.na(res_lox_interaction$padj) &
      res_lox_interaction$padj < padj_cutoff
  ]
  
  sig_haci <- rownames(res_haci_interaction)[
    !is.na(res_haci_interaction$padj) &
      res_haci_interaction$padj < padj_cutoff
  ]
  
  
  # Significant in WT-vs-lox OR WT-vs-haci
  sig_genes <- union(
    sig_lox,
    sig_haci
  )
  
  
  # -------------------------------------------------------
  # 7. Restrict to genes of interest
  # -------------------------------------------------------
  
  sig_genes <- intersect(
    sig_genes,
    goi$Gene_ID
  )
  
  
  # -------------------------------------------------------
  # 8. Get C vs W effect for WT
  # -------------------------------------------------------
  
  res_WT <- results(
    dds,
    contrast = c(
      "condition_group",
      "c",
      "w"
    )
  )
  
  
  # -------------------------------------------------------
  # 9. Get C vs W effect for lox
  # -------------------------------------------------------
  
  res_lox <- results(
    dds,
    contrast = list(
      c(
        "condition_group_c_vs_w",
        "genotypelox.condition_groupc"
      )
    )
  )
  
  
  # -------------------------------------------------------
  # 10. Get C vs W effect for haci
  # -------------------------------------------------------
  
  res_haci <- results(
    dds,
    contrast = list(
      c(
        "condition_group_c_vs_w",
        "genotypehaci.condition_groupc"
      )
    )
  )
  
  
  # -------------------------------------------------------
  # 11. Create plotting dataframe
  #
  # Keep both log2FC and lfcSE
  # -------------------------------------------------------
  
  plot_data <- bind_rows(
    
    data.frame(
      Gene_ID = sig_genes,
      genotype = "WT",
      log2FC = res_WT[sig_genes, "log2FoldChange"],
      lfcSE = res_WT[sig_genes, "lfcSE"]
    ),
    
    data.frame(
      Gene_ID = sig_genes,
      genotype = "lox",
      log2FC = res_lox[sig_genes, "log2FoldChange"],
      lfcSE = res_lox[sig_genes, "lfcSE"]
    ),
    
    data.frame(
      Gene_ID = sig_genes,
      genotype = "haci",
      log2FC = res_haci[sig_genes, "log2FoldChange"],
      lfcSE = res_haci[sig_genes, "lfcSE"]
    )
  )
  
  # ------------------------------------------------------- 
  # 12. Add interaction p-values to plotting data
  # -------------------------------------------------------
  
  plot_data <- plot_data %>%
  mutate(
    padj_lox_vs_WT = res_lox_interaction[Gene_ID, "padj"],
    padj_haci_vs_WT = res_haci_interaction[Gene_ID, "padj"]
  )
  
  
  # -------------------------------------------------------
  # 13. Create a significance label:
  # -------------------------------------------------------
  
  plot_data <- plot_data %>%
  mutate(
    significance = case_when(
      genotype == "lox" & padj_lox_vs_WT < 0.001  ~ "***",
      genotype == "lox" & padj_lox_vs_WT < 0.01   ~ "**",
      genotype == "lox" & padj_lox_vs_WT < 0.05   ~ "*",
      
      genotype == "haci" & padj_haci_vs_WT < 0.001  ~ "***",
      genotype == "haci" & padj_haci_vs_WT < 0.01   ~ "**",
      genotype == "haci" & padj_haci_vs_WT < 0.05   ~ "*",
      
      TRUE ~ ""
    )
  )
  
  # -------------------------------------------------------
  # 14. Calculate vjust in data:
  # -------------------------------------------------------
  
  plot_data <- plot_data %>%
  mutate(
    star_y = ifelse(
      log2FC >= 0,
      log2FC + 1.96 * lfcSE,
      log2FC - 1.96 * lfcSE
    ),
    star_vjust = ifelse(
      log2FC >= 0,
      -0.3,
      1.3
    )
  )
  
  
  # -------------------------------------------------------
  # 15. Add gene names
  # -------------------------------------------------------
  
  plot_data <- plot_data %>%
    left_join(
      goi %>%
        select(Gene_ID, gene_name),
      by = "Gene_ID"
    )
  
  
  # -------------------------------------------------------
  # 16. Plot
  # -------------------------------------------------------
  
  p <- ggplot(
    plot_data,
    aes(
      x = gene_name,
      y = log2FC,
      fill = genotype
    )
  ) +
    
    geom_col(
      position = position_dodge(width = 0.8)
    ) +
    
    geom_errorbar(
      aes(
        ymin = log2FC - 1.96 * lfcSE,
        ymax = log2FC + 1.96 * lfcSE
      ),
      position = position_dodge(width = 0.8),
      width = 0.25
    ) +
    
    geom_text(
      aes(
        label = significance,
        y = star_y,
        vjust = star_vjust
      ),
      position = position_dodge(width = 0.8),
      size = 4
    ) +
    
    geom_hline(
      yintercept = 0,
      linewidth = 0.5
    ) +
    
    theme_classic() +
    
    labs(
      title = segment_name,
      x = NULL,
      y = "log2 fold change (C vs W)",
      fill = "Genotype"
    ) +
    
    theme(
      axis.text.x = element_text(
        angle = 90,
        hjust = 1,
        vjust = 0.5
      )
    )
  
  
  # -------------------------------------------------------
  # 17. Return everything
  # -------------------------------------------------------
  
  return(
    list(
      dds = dds,
      significant_genes = sig_genes,
      interaction_lox = res_lox_interaction,
      interaction_haci = res_haci_interaction,
      plot_data = plot_data,
      plot = p
    )
  )
}
```


```{r}
# directly change input here

S1 <- make_segment_plot(
  segment_name = "S1",
  counts = dat_raw_counts,
  metadata = dat_meta,
  goi = dat_ph_goi
)

S2 <- make_segment_plot(
  segment_name = "S2",
  counts = dat_raw_counts,
  metadata = dat_meta,
  goi = dat_ph_goi
)

S3 <- make_segment_plot(
  segment_name = "S3",
  counts = dat_raw_counts,
  metadata = dat_meta,
  goi = dat_ph_goi
)
```

```{r}
fig_S1 <- S1$plot
fig_S2 <- S2$plot
fig_S3 <- S3$plot

fig_S1
fig_S2
fig_S3
```

```{r}
# save plots:

# pdf(
#   "S1_barplot2.pdf",
#   width = 12,
#   height = 5
# )
# 
# print(fig_S1)
# 
# dev.off()
```

## 5.2. All genes

Find all genes that have significantly different lfc between mutant and wt, for both mutants, per segment

```{r}

```






